### ISSUE TITLE
Why does few-shot require such a large video memory？

### ISSUE THREAD

**Issue by BCL123456-BAL** [Jiawei-Yang/FreeNeRF#10]
thanks for your work！
I tried to implement occlusion regularization on tensorRF, but 22G video memory is not enough for rendering test.
I want to know why the video memory within 10G in multi-view can be used for most of the nerf generation, but few shots need such video memory.

**Comment by Jiawei-Yang** [comment]
I haven't tested our method on tensorRF's codebase yet. But this is also weird to me that using occlusion regularization will increase GPU consumption. I didn't observe similar things during my experiments. 

Supporting tensorRF's codebase is currently out of the scope of this repo, but we welcome further discussions!

Free feel to re-open the issue if you have more thoughts!
