### ISSUE TITLE
Extremely slow when launching the experiments

### ISSUE THREAD

**Issue by zhongyingji** [Jiawei-Yang/FreeNeRF#11]
Hi jiawei, 
When I ran RegNeRF on Nvidia GPU, the Jax compilation stage is extremely time consuming (more than 20 minutes). I noticed that your code is based on Jax, have you ever encountered this problem? 

BTW, I also noticed that for RegNeRF, GPU consumes more than 23 GB with only batchsize 1024. Do you have any idea why is that so high?

**Comment by ntaquan0125** [comment]
@zhongyingji you should check out [this link](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html)

**Comment by zhongyingji** [comment]
Got it. Thank you: )
