### ISSUE TITLE
Novelty of frequency regularization

### ISSUE THREAD

**Issue by RohanChacko** [Jiawei-Yang/FreeNeRF#12]
Hi, 
Thanks for sharing the work. May I know how the frequency regularization is different from that proposed in barf and other papers?

Paper mentions "We note that our frequency regularization shares some similarities with the coarse-to-fine frequency schedules used in other works [23, 16]. Different from theirs, our work focuses on the few-shot neural rendering problem and reveals the catastrophic failure patterns caused by high frequency inputs and their implication to this problem". But does it have a relevant technical difference?

**Comment by Jiawei-Yang** [comment]
I think different papers have different strategies to implement frequency regularization. For example, BARF or Nefies use a sliding-window-based cosine annealing schedule. We haven't really tried to use that kind of regularization in our experiments yet.

**Comment by RohanChacko** [comment]
Have you found any benefits or performed some experiments comparing your frequency regularization against BARF/Nerfies?

**Comment by Jiawei-Yang** [comment]
That's an interesting comparison we also want to see. But we haven't been able to contribute to that due to limited time, resources, and other commitments now. I'll keep you posted if we do so. 

Thank you, Rohan!
