### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by mcs8779** [Jiawei-Yang/FreeNeRF#17]
Hi, thanks for your great work.
I want to train on my own dataset that I have, so what data would I need apart from the image files?
Could you provide some details on how to train on custom datasets?

**Comment by Jiawei-Yang** [comment]
Training with custom datasets follows a similar logic as in other NeRF projects. For example, you can follow the instructions here: https://github.com/bmild/nerf#generating-poses-for-your-own-scenes
