### ISSUE TITLE
DTU dataset download

### ISSUE THREAD

**Issue by panzhang0212** [Jiawei-Yang/FreeNeRF#2]
hello, could we need to download 123G Rectified DTU?
![image](https://user-images.githubusercontent.com/30363822/226797669-16f5f776-3cd1-4dc0-9304-1557aa496237.png)

**Comment by Jiawei-Yang** [comment]
Hi, I did download the entire dataset but I think the dataset shared by pixelNeRF's authors should also work, which is substantially smaller (1GB). You might refer to their repo or this link: https://drive.google.com/drive/folders/1PsT3uKwqHHD2bEEHkIXB99AlIjtmrEiR
