### ISSUE TITLE
 results of Google's online disk are invalidated

### ISSUE THREAD

**Issue by laparostitchData** [Jiawei-Yang/FreeNeRF#23]
Hello, the experimental results of the Google web disk are invalidated, trouble can provide new links

**Comment by brycegoh** [comment]
@Jiawei-Yang Any updates on this?

**Comment by Jiawei-Yang** [comment]
Hi, sorry for my late response! The previous link was done because I was required to clean up the google drive of that account. Please refer to this link from now on: https://drive.google.com/drive/folders/1z0cPeVRJYkdFgvlz_75oYrbRsn59-SpA?usp=sharing

The results are still being uploaded.
