### ISSUE TITLE
About frequency regularization mask in code

### ISSUE THREAD

**Issue by Pyn-hust** [Jiawei-Yang/FreeNeRF#3]
Very good job, but I have a doubt about the code. In the  function `get_freq_reg_mask` in the `math.py`, why don't you multiply the `ptr` by 3 when calculating the frequency mask fractional part?
For example:
`freq_mask[int_ptr * 3 : int_ptr * 3 + 3] =3* (ptr - int_ptr)`
Please forgive me if there is a misunderstanding.

**Comment by Jiawei-Yang** [comment]
Hi, the values in freq_mask should fall into the range of [0, 1], and `ptr - int_ptr` is the fractional part which is always within that range. Multiplying 3 doesn't make sense here.
