### ISSUE TITLE
question about freq mask code

### ISSUE THREAD

**Issue by iszihan** [Jiawei-Yang/FreeNeRF#5]
Looking at the frequency mask computation function, I'm a bit confused on this line. Wouldn't this always constraint ptr to be <2 ? How would we be able to mask more frequencies this way? 
https://github.com/Jiawei-Yang/FreeNeRF/blob/2dc3f6d766d7e0d2adf90d52903f9dcfea474cca/internal/math.py#L300

**Comment by SophusDavid** [comment]
Pos_enc_length = (L*2+1)*3. So ptr would not always be less than 2.
Maybe you can print the length of the position encoding feature.:)
