### ISSUE TITLE
question about updates in the Dietnerf folder

### ISSUE THREAD

**Issue by yiyao-zhuo** [Jiawei-Yang/FreeNeRF#7]
May I ask where the code is added specifically in the Dietnerf folder?  The content in run_ nerf.py & run_ nerf_helpers.py is consistent with the original version. And the 'get_freq_mask' function in utils.py is not applied. Thanks

**Comment by Jiawei-Yang** [comment]
Sorry about that! We just found out that we didn't push the correct `run_nerf.py`. Will update soon! We didn't modify the `run_nerf_helpers.py` file.

**Comment by yiyao-zhuo** [comment]
> Sorry about that! We just found out that we didn't push the correct `run_nerf.py`. Will update soon! We didn't modify the `run_nerf_helpers.py` file.

😘😘 hope you update soon

**Comment by Jiawei-Yang** [comment]
Hi yiyao,

Sorry for the delayed response. I will update the dietnerf part this weekend and will notify you via this thread once I'm done. I was occupied by other duties before.

**Comment by Jiawei-Yang** [comment]
Hi Yizhao,

We have updated the code for DietNeRF accordingly. Let us know if you have other questions!

Feel free to re-open the issue if needed!
