### ISSUE TITLE
Outdated python version and package conflicts

### ISSUE THREAD

**Issue by DanielSHKao** [Jiawei-Yang/FreeNeRF#8]
As Python3.6 is no longer supported by `conda` anymore (stated in the official [conda website](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html)), I used the channel `conda-forge` to build the virtual environment, which is similar to this [issue](https://stackoverflow.com/questions/64250622/can-conda-install-any-even-older-version-of-python).

However, after building the virtual environment, I found some errors while running the `requirements.txt`. The following shows the details:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/80144650/235151629-9799a669-28fb-4e3d-b2f5-4eebe05fa9a2.png">

Is there any solution to this issue? Or do you provide any updated version of the code please? Thanks.

**Comment by Jiawei-Yang** [comment]
Hi Daniel,

Had you solved the issue yet? I adhered to RegNeRF's settings and haven't tested this repo on other Python versions yet.
