### ISSUE TITLE
render.py error

### ISSUE THREAD

**Issue by DarlingHang** [Jiawei-Yang/FreeNeRF#9]
After training, `python render.py --gin_configs configs/{CONFIG} ` ran into an error while `python eval.py --gin_configs configs/{CONFIG}` didn't. This seems to be related with the definition of `render_eval_fn`.

However, when I replace `render_eval_fn` of render.py with that of eval.py, there is no error but the rendering looks unreasonable. Can the author please look into it and make render.py work normally? I am using LLFF dataset and 3 input views.

**Comment by Jiawei-Yang** [comment]
Hi there, I will try to get back to this issue soon. I'm working towards another deadline and slightly out of my bandwidth : (
I will let you know when the issue is fixed.

**Comment by Dhidbsixh** [comment]
@DarlingHang， Hi, I am a nerf beginner and I am reproducing this paper, but I met some problems about the environment installation, so I am wandering could you please show me the full packages installation of this paper? Thanks a lot.

**Comment by DeepDream1128** [comment]
I have found the same problem, and I tried to replace `models.py` with the version in the RegNeRF, it worked but the result was also not very reasonable.

**Comment by Jiawei-Yang** [comment]
Hi guys, sry for the inconvenience. I’ll update this function this weekend! I was overwhelmed by another deadline before

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DeepDream1128** [comment]
Thank you! And now I find it can work by changing 

```
def render_eval_fn(variables, _, rays):
    return jax.lax.all_gather(
        model.apply(
            variables,
            None,  # Deterministic.
            rays,
            resample_padding=config.resample_padding_final,
            compute_extras=True),
        axis_name='batch')
```

into
```
def render_eval_fn(variables, _, rays):
    return jax.lax.all_gather(
        model.apply(
            variables,
            None,  # Deterministic.
            rays,
            resample_padding=config.resample_padding_final,
            compute_extras=True)[0], # I don't know why and what is contained in it, and I only know the num can only be 0 or 1
        axis_name='batch')
```
However, I don't know if it affect the result

**Comment by Jiawei-Yang** [comment]
Hi guys, I have updated the `render.py`. See `sample_scripts/render_dtu.sh` for details. 
You need to install `mediapy==1.0.0` to make the `create_videos` function work.

Let me know if you have more questions!

**Comment by Jiawei-Yang** [comment]
> Thank you! And now I find it can work by changing
> 
> ```
> def render_eval_fn(variables, _, rays):
>     return jax.lax.all_gather(
>         model.apply(
>             variables,
>             None,  # Deterministic.
>             rays,
>             resample_padding=config.resample_padding_final,
>             compute_extras=True),
>         axis_name='batch')
> ```
> 
> into
> 
> ```
> def render_eval_fn(variables, _, rays):
>     return jax.lax.all_gather(
>         model.apply(
>             variables,
>             None,  # Deterministic.
>             rays,
>             resample_padding=config.resample_padding_final,
>             compute_extras=True)[0], # I don't know why and what is contained in it, and I only know the num can only be 0 or 1
>         axis_name='batch')
> ```
> 
> However, I don't know if it affect the result

This will provide the same results once all frequency bands are visible. But to render an intermediate checkpoint, e.g., a ckpt before the end of frequency regularization, this modification will fail. Kindly refer to our updated function for a workaround.

**Comment by Jiawei-Yang** [comment]
Feel free to re-open the issue if needed!
